### ISSUE TITLE
Review all roles and permissions to ensure everything is "least-privileged" 

### ISSUE THREAD

**Issue by LilaKelland** [PHACDataHub/cpho-phase2#100]
We're using broader scoped roles and permissions to get things up and running at the moment, but once we're closer to finalizing the infrastructure we'll want to review all the roles and permissions to limit access and capabilities to the bare-minimum. 

https://cloud.google.com/iam/docs/using-iam-securely#least_privilege

I think @tcaky has been looking at this as well.

**Comment by Stephen-ONeil** [comment]
Rather than reviewing the current GCP project's IAM, we'll be starting from scratch with enforced least-privileged in the new "noble experimentation" project space.
