### ISSUE TITLE
Update architecture diagram

### ISSUE THREAD

**Issue by LilaKelland** [PHACDataHub/cpho-phase2#101]
With:
- [ ] Test coverage reporting
- [x] Alerts 
- [x] OpenTelemetry

**Comment by Stephen-ONeil** [comment]
I'm considering adding the OpenTelemetry component too, although it's going to get very cluttered if we capture everything in one go. I've been meaning to check if there's a way we could do something like identify objects/connections as part of different layers, that we could toggle on and off :thinking:

**Comment by Stephen-ONeil** [comment]
OpenTelemetry is in the architecture diagram now.

**Comment by Stephen-ONeil** [comment]
Added slack alerting too. Closing and adding a note to the test coverage issue to include it in the architecture diagram, once the solution exists.
