### ISSUE TITLE
Pre-prod (dev/test) environment

### ISSUE THREAD

**Issue by Stephen-ONeil** [PHACDataHub/cpho-phase2#138]
There's going to be a need for a dev/test environment to (user) test new features in a prod-like environment. 

GitOps wise, I'd suggest having the main branch syncing to the dev/test environment and a separate prod branch for the prod state. @AlexCLeduc any considerations from your perspective?

The dev/test environment would ideally use fake data, re-seeded periodically (on every deploy maybe). That'd put the onus on the devs to maintain seeding scripts or fake data factories, so that's also @AlexCLeduc's call. Could also just leave the manual management of the dev/test environment's database to the devs.

On the DevOps side, we'll need to figure out how to best enable this. There's a lot about the k8s side of this that aren't obvious to me, so if you have a good idea, chime in @simardeep1792 @vedantthapa!

**Comment by AlexCLeduc** [comment]
I would prefer an explicit branch for each environment, including dev, just so we're never worried about merging good stuff to main and updating what is currently being tested

Same thing for seeding, I think a manual approach is best for flexibility sake

**Comment by Stephen-ONeil** [comment]
Worth noting, I see this as filling in the missing final readiness-check piece of the prod deployment picture. We could do canary deploys in the prod cluster with something like [flagger](https://flagger.app) (sibling to Flux), but database migrations make this a difficult proposition for us. Having a separate cluster with its own database where new app code can be tested "in prod" alongside its intended migrations is simpler and safer in practice.

**Comment by Stephen-ONeil** [comment]
Addressed by ephemeral deployments in general, and the dedicated dev-test deployment (#214) in particular.
