### ISSUE TITLE
Add coverage reporting for the server

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cpho-phase2#17]
Python's unittest tool [can calculate test coverage](https://www.pythontutorial.net/python-unit-testing/python-unittest-coverage/), and we should get that going with a [pdm post-script](https://pdm.fming.dev/latest/usage/scripts/#pre-post-scripts).

**Comment by tomcdona** [comment]
@sleepycat can you take a look at some of the unit tests that have been built for ITAP? some of those ITAP unit tests will be feeding the SRTM evidence packages, it would be good to get a standard going in the phac-helpers repo. 
@lucbelliveau who else would be a good add to get the helpers library refactored to start producing evidence from unit tests?

**Comment by sleepycat** [comment]
@tomcdona I'll take a look! (the results of the looking would show up in future PRs though)

**Comment by lucbelliveau** [comment]
@tomcdona anyone who uses python and write unit tests!  But unit tests are very specific to the app... But things like code coverage and how to expose the results to GitHub would be pretty standard boilerplate...  I'm not sure how replacing one boilerplate recipe with another one is better?  Depends what can be moved into a third party library...

**Comment by tomcdona** [comment]
my brain keeps dragging me back to the SRTM insanity. Between all the work going on in ITAP, and I've noticed some neat stuff going in with the [Web App Platform](https://github.com/PHACDataHub/web-app-platform) that @Mexmorize and @daneroo are working on, I guess my top hope is to be able to generate evidence easily and quickly as much as we can...

**Comment by sleepycat** [comment]
Closed by 5fd7800
