### ISSUE TITLE
Add linting to the server

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cpho-phase2#19]
Adding linting to projects is a great way to catch errors and ensure the code quality stays high. 
[Ruff](https://beta.ruff.rs/docs/) is a linter for python that is written in [Rust](https://www.rust-lang.org/) and extremely fast.
Adding it to the server (as a [pdm script](https://pdm.fming.dev/latest/usage/scripts/) initially) would be  useful both during development (where tools like [Ale](https://github.com/dense-analysis/ale#asynchronous-lint-engine---) or a [VSCode extension](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff) surface linting errors as you type), and also in the CI pipeline that we'll be creating shortly.

**Comment by andGuo** [comment]
Hey I am interested in this project. May I take this ticket? 

Do you have any repo specific considerations or is the [ruff default](https://github.com/charliermarsh/ruff#configuration) configuration okay?

**Comment by alemgeb** [comment]
hello @andGuo, I believe I am assigned to this issue but waiting on confirmation from owner

**Comment by alemgeb** [comment]
@andGuo  the ticket is yours, and the ruff default config is good

**Comment by tomcdona** [comment]
Hey All, just a heads up we've also got a full backlog running in DevOps for this project
https://dev.azure.com/HCPHAC/National%20Surveillance%20Project/_backlogs/backlog/CPHO/Epics

Let me know if you want access, I just need your phac accounts.
