### ISSUE TITLE
CPHO: Add OpenTelemetry to server

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cpho-phase2#23]
OpenTelemetry is an open observability standard. [Google's Cloud Trace works with OT](https://cloud.google.com/trace/docs/setup/python-ot) and there is [a library](https://opentelemetry-python.readthedocs.io/en/latest/examples/django/README.html) that automatically instruments Django applications. We should get this working on the CPHO server.

**Comment by LilaKelland** [comment]
There's a plugin for OpenTelemetry: https://pypi.org/project/pytest-opentelemetry/
