### ISSUE TITLE
Unleash Dependabot! :robot: 

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cpho-phase2#25]
Let's get dependabot going in this repo! Dependabot is pretty enthusiastic so [limiting it to some sane number of PRs](https://github.com/canada-ca/tracker/blob/master/.github/dependabot.yml#L1-L8) is a good idea, but once that's in place it's just a matter of enabling it in [repository config](https://github.com/PHACDataHub/safe-inputs/settings/security_analysis):
![image](https://user-images.githubusercontent.com/109692/213017754-85d9e550-5308-4629-b9c4-212cd47b12a9.png)

**Comment by LilaKelland** [comment]
Looks like you might need admin access to enable Dependabot - @AlexCLeduc can you enable this?
![image](https://github.com/PHACDataHub/cpho-phase2/assets/38951930/f194586c-9bd1-4946-8ec0-90086f7963b8)

@Stephen-ONeil brought up a valid point that the dependency versions for these projects will generally be inline with the versions in helper repo and template project.

**Comment by LilaKelland** [comment]
PR #53 - Added basic config (copied from tracker - looks at pip, Dockerfile and cloudbuild.yaml dirs).  Question is how to we balance keeping versions inline with the PHAC Django helper functions and updating for security -  and do we need to assign the dependabot PRs to an individual (maybe repo owner?) to ensure they get merged?

**Comment by lucbelliveau** [comment]
> PR #53 - Added basic config (copied from tracker - looks at pip, Dockerfile and cloudbuild.yaml dirs). Need to follow-up with @lucbelliveau when he's back re syncing PHAC helper dependency versions.

I'm back...
