### ISSUE TITLE
Automatically run server migrations

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cpho-phase2#35]
We need to figure out a way of automatically running migrations for the server.
 
There is some [existing code](https://github.com/PHACDataHub/cpho-phase2/blob/b3eb39765797ffaf81fd1b55c4cc29ba1e8a941f/server/kubernetes/deployment.yaml#L19-L90) from an initial attempt in the deployment for the server. The thinking was to use an initContainer, but it wasn't working for some reason. Historically [istio's sidecars can conflict](https://github.com/istio/istio/issues/32039#issuecomment-1316108623) with running migrations from an initContainer but the exact cause isn't clear.

Totally open to other solutions like jobs here too.

**Comment by Stephen-ONeil** [comment]
The istio issue doesn't apply to the current state of the repo. A solution exists, with un-run migrations happening on Cloud Run container launch. Further discussion for handling more advanced migration/data maintenance issues to happen in 64
