### ISSUE TITLE
GraphiQL is not loading

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/cpho-phase2#38]
[Graphene Django](https://docs.graphene-python.org/projects/django/en/latest/tutorial-plain/#creating-graphql-and-graphiql-views) includes the web based GraphQL IDE [GraphiQL](https://github.com/graphql/graphiql#graphiql).
It should be available at `/graphql` but currently the files needed for it to work are producing a 404. 

The [most likely cause](https://github.com/graphql-python/graphene-django/issues/685#issuecomment-517173277) here is a missing `manage.py collectstatic` step in the build process.
![image](https://github.com/PHACDataHub/cpho-phase2/assets/109692/2eab3080-91c0-4f45-b35a-e0eda848e89c)

**Comment by Stephen-ONeil** [comment]
Resolved in current instance
