### ISSUE TITLE
Add test coverage reporting

### ISSUE THREAD

**Issue by LilaKelland** [PHACDataHub/cpho-phase2#54]

**Comment by LilaKelland** [comment]
The coverage.py & pytest-cov packages are already included in this repo and with:
```
coverage run manage.py test
coverage report
```
we can get:
<img width="821" alt="image" src="https://github.com/PHACDataHub/cpho-phase2/assets/38951930/5eafe97a-e0d5-4f62-a005-9aa52439726a">

@sleepycat are we looking to measure a particular threshold, or auto report when run?  I imagine we'll want to skip particular files and maybe include missing lines? (was looking at [django-nose](https://django-testing-docs.readthedocs.io/en/latest/coverage.html), but this seems similar.)

**Comment by LilaKelland** [comment]
@Stephen-ONeil suggested using something like [code coverage](https://about.codecov.io/) and including badges like used [here](https://github.com/TBS-EACPD/infobase).

**Comment by tomcdona** [comment]
@LilaKelland @Stephen-ONeil @sleepycat we've got a LOT of this going in the [ITAP repo](https://github.com/PHACDataHub/data-collection), check it out 👍 

We've launched to Production with the main branch in the repo, so it's had a long time to mature, take what you can for here

**Comment by LilaKelland** [comment]
Merging with this with issue #55 (Add testing as a step in the deployment process) into issue #60 (Testing, and test coverage reporting as a Cloud Build step).

**Comment by Stephen-ONeil** [comment]
Oops, I should have reviewed what issues already existed before I opened that new one :sweat_smile:. Thanks!
