### ISSUE TITLE
Add coverage reports for templates.

### ISSUE THREAD

**Issue by LilaKelland** [PHACDataHub/cpho-phase2#74]
This issue came out of PR #73 (Testing as a Cloud Build step and code coverage reporting.)  

Stephen made this [comment ](https://github.com/PHACDataHub/cpho-phase2/pull/73#discussion_r1269774930)"...there's a coverage plugin called django_coverage_plugin we can add to possibly get coverage reports on django templates as well. Note, the example I saw this in was using django's built in templates, while this project is using jinja for templating. Haven't checked if this specific plugin can also track coverage for jinja files, or if some jinja alternative exists."

**Comment by Stephen-ONeil** [comment]
No options right now, as per Alex's comment. Closing.
