### ISSUE TITLE
Age group records shouldn't be deleted 

### ISSUE THREAD

**Issue by AlexCLeduc** [PHACDataHub/cpho-phase2#91]
Currently we rely on the formset logic to delete age groups that get checked "deleted". Right now it is actually deleting records and all of their versions. We need to override this behaviour and probably modify the data-model to keep its versions around.

**Comment by AlexCLeduc** [comment]
1. Add a `is_deleted` boolean field on `IndicatorDatum` and a `soft_delete()` method. 
2. Modify (probably some hacky override of private methods involved 😞 ) the age-group formset to soft-delete records when the delete field is set
3. Add an 'active_objects' manager to the indicator datum 
4. Change a bunch (but not all?) of `IndicatorDatum.objects` to `IndicatorDatum.active_objects`
    5. and probably related managers too (`indicator.data` to `indicator.data.filter(is_deleted=False)`), this might also mess up some eager-loading and cause N+1 issues

**Comment by msarar** [comment]
After initial discussion:

We decided to remove the form.DELETE method for the formset as we can use the is_deleted boolean on the indicatordatum model and have some logic to hide the deleted fields. (this way we wont add extra code complexity of overriding save_existing_objects method in the inlineformset class)
 
We realized that uniqueness might create an issue if the user decides to delete the same agegroup form (same key values) twice.
So we can also add a deleted_on field and add it in the unique_together property
